[package]
name = "Day07"
version = "0.1.0"
authors = ["Hugo Chen <hugo.chen@telexpress.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
